### ISSUE TITLE
Not an Issue but a Question :) 

### ISSUE THREAD

**Issue by beflo-ger** [SAP-samples/teched2020-IIS201#1]
Hello everyone,
I listened to your presentation on YouTube and would like to take my first steps on the ScreenPeersonas system myself. The system is offline, will there soon be a new presentation or the possibility to replay your tasks?

Many thanks for an answer and looking forward to hear from you!

With kind regards

Florian

P.S. Great presentation, looking forward to more!

**Comment by thoznek** [comment]
The system is being upgraded to the latest S/4HANA 2020 release, but unfortunately the process takes way longer than we anticipated. I don't have an exact ETA, but trying to push this process as much as I can. 
Hopefully soon...

**Comment by thoznek** [comment]
Finally, after all maintenance activities the system is available again.
